config/routes.rb
Rails.application.routes.draw do
  resources :schools
end

app/models/school.rb
require "ostruct"

class School
  def self.service
    @service ||= SchoolistService.new
  end

  def self.all
    service.schools.map { |school| _build_object(school) }
  end

  def self.find(id)
    _build_object(service.school(id))
  end

  def self.create(params)
    _build_object(service.create_school(params))
  end

  def self.update(id, params)
    service.update_school(id, params)
  end

  def self.destroy(id)
    service.destroy_school(id)
  end

  def self._build_object(data)
    OpenStruct.new(data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params[:id])
  end

  def new
  end

  def create
    @school = School.create(params)

    redirect_to school_path(@school.id)
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    School.update(params[:id], params)

    redirect_to school_path(params[:id])
  end

  def destroy
    School.destroy(params[:id])

    redirect_to schools_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obeset</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/edit.html.erb
<%= form_tag("/schools/#{@school.id}", method: :put) do %>
  <%= label_tag "uid" %>
  <%= text_field_tag "school[uid]", @school.uid %>
  <%= label_tag "overweight_percentage" %>
  <%= text_field_tag "school[overweight_percentage]", @school.overweight_percentage %>
  <%= label_tag "obese_percentage" %>
  <%= text_field_tag "school[obese_percentage]", @school.obese_percentage %>
  <%= submit_tag "Create" %>
<% end %>

app/views/schools/index.html.erb
<% @schools.each do |school| %>
  <h2><%= school.uid %></h2>
  <p><%= school.overweight_percentage %></p>
  <p><%= school.obese_percentage %></p>
  <p><%= link_to "Delete", school_path(school.id), method: :delete %></p>
  <p><%= link_to "Edit", edit_school_path(school.id) %></p>
<% end %>

app/views/schools/new.html.erb
<%= form_tag "/schools", method: :post do %>
  <%= label_tag "uid" %>
  <%= text_field_tag "school[uid]" %>
  <%= label_tag "overweight_percentage" %>
  <%= text_field_tag "school[overweight_percentage]" %>
  <%= label_tag "obese_percentage" %>
  <%= text_field_tag "school[obese_percentage]" %>
  <%= submit_tag "Create" %>
<% end %>

app/views/schools/show.html.erb
<h2><%= @school.uid %></h2>
<p><%= @school.overweight_percentage %></p>
<p><%= @school.obese_percentage %></p>